import fs from 'node:fs';
import path from 'node:path';

export const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const external = (url, text, cls = '') => `<a ${cls ? `class="${cls}" ` : ''}href="${escape(url)}" target="_blank" rel="noopener noreferrer">${escape(text)}<span class="sr-only"> (opens in a new tab)</span><span aria-hidden="true"> ↗</span></a>`;
const button = (href, text, primary = false) => `<a class="button${primary ? ' primary' : ''}" href="${href}">${text}<span aria-hidden="true"> →</span></a>`;
const tag = (text, variant = '') => `<span class="tag ${variant}">${escape(text)}</span>`;
const intro = (eyebrow, title, description) => `<section class="page-intro wrap"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lede">${description}</p></section>`;
const note = (title, body, variant = '') => `<aside class="note ${variant}"><strong>${title}</strong><p>${body}</p></aside>`;
const section = (id, title, body, description = '') => `<section class="section wrap" id="${id}"><div class="section-heading"><h2>${title}</h2>${description ? `<p>${description}</p>` : ''}</div>${body}</section>`;
const code = command => `<div class="code-block"><pre><code>${escape(command)}</code></pre><button class="copy-button" type="button" aria-label="Copy command">Copy</button></div>`;
const table = (headers, rows, caption = '') => `<div class="table-scroll" tabindex="0" role="region" aria-label="${escape(caption || headers.join(', '))}"><table>${caption ? `<caption>${caption}</caption>` : ''}<thead><tr>${headers.map(h => `<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr>${row.map(c => `<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const figure = (asset, alt, caption, cls = '') => `<figure class="diagram ${cls}"><a href="/assets/${asset}" aria-label="Open full-size ${escape(alt)}"><img src="/assets/${asset}" alt="${escape(alt)}" loading="lazy"></a><figcaption>${caption} <a href="/assets/${asset}">Open full-size diagram ↗</a></figcaption></figure>`;
const pathName = file => file === 'index.html' ? '/' : `/${file}`;

export function layout(page, {config, release}) {
  const navigation = [['index.html','Project'],['architecture.html','Architecture'],['research.html','Research'],['evidence.html','Evidence'],['demo.html','Demo']];
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(page.title)} · VisionX</title><meta name="description" content="${escape(page.description)}"><meta name="theme-color" content="#f7f8f6"><link rel="canonical" href="${config.canonicalUrl}${pathName(page.file)}"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><script src="/script.js" defer></script></head>
<body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="wrap nav-row"><a class="brand" href="/" aria-label="VisionX home"><img class="brand-logo" src="/assets/visionx-eye-emblem-logo.webp" alt="VisionX Eye Emblem Logo"><span class="brand-sub">Team Synexis · SIH26215</span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="primary-navigation">Menu <span aria-hidden="true">☰</span></button><nav id="primary-navigation" aria-label="Primary navigation">${navigation.map(([file,label]) => `<a href="${pathName(file)}"${page.file === file ? ' aria-current="page"' : ''}>${label}</a>`).join('')}</nav></div></header>
<main id="main">${page.content}</main>
<footer class="site-footer"><div class="wrap footer-grid"><div><a class="footer-brand" href="/" aria-label="VisionX home"><img class="footer-brand-logo" src="/assets/visionx-eye-emblem-logo.webp" alt="VisionX"></a><p>Personal route memory research.<br>One junction. Two taught branches.</p><p class="small">Release ${escape(config.releaseVersion)} · 1 October 2026 (IST)<br>Source identity: <a href="/evidence/release.json"><code>${release.sourceSha256.slice(0,12)}</code></a></p></div><nav aria-label="Technical documentation"><strong>Inspect</strong><a href="/evidence.html">Executed evidence</a><a href="/source.html">Release source excerpts</a><a href="/reproduce.html">Reproduction guide</a>${external(config.repositoryUrl,'Upstream repository')}</nav><nav aria-label="Project context"><strong>Context</strong><a href="/business.html">Proposed business model</a><a href="/references.html">Research references</a><a href="/docs/claim-evidence-matrix.md">Presentation claim register</a><a href="/docs/audit/analysis.md">Artifact audit</a></nav></div><div class="wrap footer-bottom"><span>© 2026 Team Synexis CU-UP · Team ID 190125</span><span>Research evidence does not establish validated navigation or user benefit.</span></div></footer><div id="copy-status" class="sr-only" aria-live="polite"></div></body></html>`;
}

export function pages(context) {
  const {config, release, reports, status, root} = context;
  const repo = external(config.repositoryUrl, 'Inspect upstream repository', 'button');
  const defaultMetrics = reports.notebook04.methods.vxn_default.metrics;
  const statusRows = status.capabilities.map(c => [escape(c.capability), tag(c.status, c.category === 'core' ? 'core' : c.category === 'team_report' ? 'reported' : 'target'), escape(c.boundary)]);
  const make = (file, title, description, content) => ({file, title, description, content});
  const home = make('index.html', 'Learned-route research, inspectable evidence', 'VisionX taught-route assistance research: offline VXN-RAMNet core, team-reported Pi-to-Android detection, executable benchmarks and clear limits.', `
<section class="hero wrap"><div class="hero-copy"><p class="eyebrow">VisionX · Smart India Hackathon 2026</p><h1>Recognizing taught routes<br class="hero-br">with visual memory.</h1><p class="lede">VisionX explores route assistance for blind and low-vision travelers. Its VXN-RAMNet core learns a bounded route memory from video and returns a known branch, uncertainty, or an unknown-route result.</p><div class="actions">${button('/evidence.html','Inspect the evidence',true)}${button('/demo.html','Open the demo')}</div><p class="hero-footnote">Offline route research · team-reported live object detection · mobile route integration in progress</p></div><div class="hero-media-card" aria-label="Smart glasses wearable prototype 360 preview"><video class="hero-glasses-video" autoplay loop muted playsinline preload="auto"><source src="/assets/smart-glasses-turntable.webm" type="video/webm">Your browser does not support the video tag.</video></div></section>
<div class="evidence-strip"><div class="wrap strip-grid"><div><strong>1 junction / 2 branches</strong><span>Implemented topology</span></div><div><strong>${defaultMetrics.journeys} cached fixture queries</strong><span>Regression diagnostics only</span></div><div><strong>${release.verification.pytest.tests} passing tests</strong><span>Actual local verification</span></div><a href="/reproduce.html">Reproduce the core <span aria-hidden="true">→</span></a></div></div>
${section('scope','Three distinct evidence boundaries', `<div class="three-columns"><article class="feature"><span class="section-number">01</span>${tag('Implemented + tested','core')}<h3>Offline route-memory core</h3><p>Completed learning and query videos, frozen EfficientNetB0 features, constrained route components, multi-window branch evidence, versioned artifacts and explicit abstention.</p><a href="/research.html">Read the implemented method →</a></article><article class="feature"><span class="section-number">02</span>${tag('Team-reported hardware test','reported')}<h3>Pi-to-Android detection</h3><p>Pi Zero 2 W, camera and VL53L0X feed the Java/XML Android app over a Pi hotspot. YOLOv8s detections reach phone TTS and headphones. The team reports up to approximately one hour of testing.</p><p class="small">Pi/app source and session measurements were not supplied for independent execution.</p></article><article class="feature"><span class="section-number">03</span>${tag('Integration + future work','target')}<h3>Live route assistance</h3><p>VXN-RAMNet on Android is in progress according to the presentation. Causal route inference, physical turn timing, IMU fusion, freshness policy and supervised user benefit remain unvalidated.</p><a href="/architecture.html">Inspect the system boundary →</a></article></div>`)}
${section('workflow','A taught route becomes inspectable memory', `<div class="split-layout"><div><p>The current core builds memory rather than training a new neural network. It stores common path, junction, Branch A, backtrack and Branch B components, then compares later query windows against them.</p>${note('The branch label has a narrow meaning','Branch A and Branch B identify exploration order. They do not establish physical left/right, a safe path, or when a turn should be announced.')}<div class="actions">${button('/architecture.html','Architecture and diagrams')}${button('/source.html','Inspect release source')}</div><div class="route-board" aria-label="Implemented offline enrollment sequence"><div class="board-heading"><span>VXN-RAMNet</span>${tag('Offline research core','core')}</div><p class="board-label">One structured teaching journey</p><ol class="route-trace"><li><span class="trace-node" aria-hidden="true">01</span><div><strong>Common path</strong><span>Shared approach to a learned junction</span></div></li><li><span class="trace-node" aria-hidden="true">02</span><div><strong>Junction</strong><span>Visual revisit inference</span></div></li><li><span class="trace-node" aria-hidden="true">A</span><div><strong>First taught branch</strong><span>Turnaround and backtrack</span></div></li><li><span class="trace-node" aria-hidden="true">↶</span><div><strong>Return to junction</strong><span>Same enrollment recording</span></div></li><li><span class="trace-node" aria-hidden="true">B</span><div><strong>Second taught branch</strong><span>Labels describe exploration order</span></div></li></ol><div class="board-output"><span>Query outcome</span><strong>Known / Uncertain / Unknown</strong><small>Heuristic thresholds. No physical turn instruction.</small></div></div></div>${figure('presentation/VisionX_01_Proposed_Solution.svg','VisionX teaching and recognition workflow with current and target paths','Supplied presentation workflow. Solid and dashed paths retain their implementation status.')}</div>`)}
${section('judge-path','A short path for technical review', `<ol class="review-steps"><li><a href="/docs/claim-evidence-matrix.md"><strong>Presentation claim</strong><span>Slide-by-slide traceability register</span></a></li><li><a href="/source.html"><strong>Implementation</strong><span>Exact package source from this release</span></a></li><li><a href="/evidence.html"><strong>Tests and evaluation</strong><span>Counts, failures, denominators and timing scope</span></a></li><li><a href="/reproduce.html"><strong>Reproducible evidence</strong><span>Commands, manifests and checksums</span></a></li></ol><p class="small">SIH deployment is intentionally compact: judge-facing reports, CSVs, plots, verification records, complete package source and readable tests stay online. Bulk NPZ arrays and hundreds of per-query diagnostic JSON files are preserved in one checksummed archive in the source package and excluded from Vercel.</p>`)}
${section('limits','The next proof is independent-session evaluation', `<p>The delivered benchmarks exercise cached regression fixtures and generated vector stress cases. They provide measurable software evidence, while representative camera-route accuracy and unknown-route rejection still need a held-out dataset.</p><p>Potential accessibility, economic and environmental benefits remain hypotheses. No clinical effect, safety certification, market superiority or user-trial result is claimed.</p><div class="actions">${button('/evidence.html','See actual numeric results',true)}${button('/references.html','Prior art and research')}${button('/business.html','Conditional deployment model')}</div>`)}
`);

  const architecture = make('architecture.html','Architecture and implementation boundaries','Presentation-aligned VisionX system architecture, current hardware test, implemented offline VXN-RAMNet pipeline and proposed route integration.', intro('Architecture · presentation alignment','Hardware detection and route research<br>are separate execution paths.','The supplied presentation reports a working capture/detection prototype. This repository implements the offline route-memory core. Connecting them into live route guidance still requires defined contracts and validation.') +
    section('system','VisionX system architecture', figure('presentation/VisionX_02_System_Architecture.svg','VisionX system architecture: team-reported Pi camera and VL53L0X to Android YOLOv8s and TTS, separate offline VXN-RAMNet, planned IMU and route-output policy','Original supplied SVG, preserved byte-for-byte. Hardware “implemented” labels reflect the team account, not this review’s bench measurements.')) +
    section('current-paths','What runs where', table(['Execution path','Current role','Evidence boundary'],[
      ['Pi Zero 2 W + camera + VL53L0X','Capture and distance acquisition; local Wi-Fi access point','Working status and approximately one-hour stream test are team-reported. No packet, latency, battery or thermal logs were supplied.'],
      ['Java/XML Android app + YOLOv8s + TTS','Scan, connect, verify; receive camera/distance; speak detections','Temporary object-detection integration test. Android/Pi source is outside this repository.'],
      ['Python VXN-RAMNet + EfficientNetB0','Offline enrollment and completed-video branch recognition','Implemented research package. Tested with injected descriptors, cached fixture and real encoder smoke tests.'],
      ['VXN-RAMNet mobile integration','Intended Android route-memory inference','In progress in the supplied presentation. Mobile conversion parity and causal route runtime are unvalidated.'],
    ])) +
    section('status','Implementation status register',table(['Capability','Status','Boundary'],statusRows)) +
    section('core','Implemented core: enrollment and recognition', `<div class="two-columns"><article class="method"><h3>Enrollment</h3><ol><li>Validate and sample a completed teaching video.</li><li>Encode original and horizontally flipped frames.</li><li>Search for junction revisits and a turnaround.</li><li>Segment the constrained five-component memory.</li><li>Save numeric arrays, metadata and checksums.</li></ol></article><article class="method"><h3>Recognition</h3><ol><li>Read a completed query video or cached descriptors.</li><li>Compare candidate windows to branch and shared components.</li><li>Aggregate selected diverse windows.</li><li>Apply heuristic strength and separation thresholds.</li><li>Return a known branch, uncertainty or unknown route with evidence.</li></ol></article></div>${note('Enrollment quality also gates acceptance','A low-quality inferred graph now withholds known-branch acceptance. This is an engineering guard, not calibrated safety confidence.')}<div class="actions">${button('/source.html#recognition','Inspect the shared numerical API')}${button('/research.html','Equations and evaluation design')}</div>`) +
    section('stack','Technology roles, without implied runtime completion', figure('visionx-technology-stack-infographic.webp','VisionX Technology Stack Infographic: implemented Java XML Android test, offline Python TensorFlow Keras Streamlit core, temporary YOLOv8s and planned integration','VisionX technology stack infographic. Logos identify roles; they do not validate mobile route inference.')) +
    `<section class="section wrap" id="hardware"><div class="split-layout"><div><div class="section-heading"><h2>Supplied component inventory</h2></div><figure class="component-photo"><img src="/assets/components.jpeg" alt="Supplied component inventory photo with Pi-format board, camera ribbon, loose modules and cables" loading="lazy"><figcaption>Inventory photo only. It does not establish wiring, module identity for every part, battery runtime or an executed session.</figcaption></figure></div><div><h3>Sensor terminology matches the PPT</h3><p>The current team account names a <strong>VL53L0X time-of-flight sensor</strong>. Earlier HC-SR04 and bone-conduction references are historical design alternatives. The photo’s HC-SR04 module does not make it the fitted sensor in the reported test.</p><p>IMU acquisition through the Pi and turn/backtrack fusion are planned. Power, enclosure, stream freshness and fault handling need measured evidence.</p>${note('Proximity is a separate channel','A range observation does not establish path clearance, stairs, drop-offs, traffic safety or collision avoidance.')}<div class="hardware-media-card" aria-label="Smart glasses exploded view diagram animation"><video class="hardware-glasses-video" autoplay loop muted playsinline preload="auto"><source src="/assets/smart-glasses-exploded-view.webm" type="video/webm">Your browser does not support the video tag.</video></div></div></div></section>` +
    section('future','Contracts still needed for live assistance', `<ul class="detail-list"><li><strong>Progress and physical direction:</strong> destination, incoming approach, intended outgoing edge, trigger zone and cue age.</li><li><strong>Data freshness:</strong> acquisition timestamps, session/sequence IDs, bounded queues, loss/reorder and reconnect behavior.</li><li><strong>Output policy:</strong> separate route, proximity and fault channels; cancel stale route speech; accessible stop and recovery.</li><li><strong>Mobile proof:</strong> descriptor parity, ranking parity, causal processing and sustained latency, memory, power and thermal measurements.</li><li><strong>User proof:</strong> supervised co-design and trials alongside established mobility aids.</li></ul>`));

  const research = make('research.html','Implemented method and evaluation design','VXN-RAMNet equations, reproducible baseline comparison, leakage controls, abstention metrics and explicit scientific limitations.', intro('Research core · methodology','Evaluating branch recognition<br>within a constrained route.','The research question is whether structured route memory and window evidence add useful branch discrimination beyond simpler retrieval or sequence methods on independently recorded journeys.') +
    section('method','What the algorithm actually computes', `<div class="method-stack"><article><h3>Frozen representation</h3><p>Keras EfficientNetB0, global average pooling, RGB 224×224 by default, original/flip descriptors and unit L2 normalization. Enrollment stores descriptors; it does not retrain a new VXN neural architecture.</p></article><article><h3>Flip-aware similarity</h3>${code('S(i,j) = max(aᵢ·bⱼ, aᶠᵢ·bⱼ, aᵢ·bᶠⱼ, aᶠᵢ·bᶠⱼ)')}<p>Near-diagonal matches are suppressed for enrollment revisit search. Horizontal flipping does not create unseen reverse-facing camera views.</p></article><article><h3>Component evidence</h3>${code('frame evidence = 0.50 × best match\n               + 0.30 × mean of strongest three matches\n               + 0.20 × centroid similarity\ncomponent score = mean frame evidence')}<p>Common path and junction evidence influence window selection. The stored backtrack component is not used directly in final query scoring.</p></article><article><h3>Window aggregation and acceptance</h3>${code('window quality = best branch + 0.70 × branch gap\n                 − 0.25 × shared evidence + 0.03 × start/N\nknown candidate: best branch ≥ 0.58 and branch gap ≥ 0.04')}<p>Earlier unknown and ambiguity rules also apply. The confidence field remains an uncalibrated heuristic. Candidate windows are selected from completed queries, so this result does not measure live decision delay.</p></article></div>`) +
    section('comparisons','Baselines and ablations implemented in this release', table(['Method','Comparison role','Qualification'],[
      ['Window recomputation reference','Numeric/runtime parity','Same component arithmetic, compared with default reuse of per-frame scores.'],
      ['Fixed Branch A','Forced-choice lower reference','Predeclared; never chosen by looking at test label frequencies.'],
      ['Global centroid','Compact branch representation','Scores have a different distribution; shared thresholds are not separately calibrated.'],
      ['Last-frame nearest neighbor','One-frame retrieval reference','Last frame is fixed in advance, not selected after reading labels.'],
      ['Mean nearest neighbor','Simple multi-frame retrieval','Same learned memory, using the query suffix.'],
      ['DTW suffix','Sequence alignment reference','Global alignment with at most 64 samples per sequence; not a SeqSLAM reproduction.'],
      ['Disjoint best / legacy / original-only / no temporal prior','Policy and representation ablations','No parameter tuning on these evaluation cases.'],
    ]) + `<div class="actions">${button('/evidence.html','Inspect every method result',true)}${button('/source.html#evaluation','Read evaluator source')}</div>`) +
    section('protocol','A held-out study still requires new acquisitions', `<div class="two-columns"><article><h3>Leakage controls</h3><p>Split complete journeys by acquisition session and, where relevant, participant or layout. Keep development, calibration and final test data separate. Do not split nearby frames as independent samples.</p><p>The manifest loader checks session separation for declared held-out runs, input hashes, duplicate files/content, unique IDs and contained paths. Metadata assertions still need trustworthy collection records.</p></article><article><h3>Primary measures</h3><ul class="detail-list"><li>Known branch decisions and macro F1, counting abstentions as missed known labels.</li><li>Accepted errors together with coverage.</li><li>Unknown false acceptance and score ranking, when unknown cases exist.</li><li>Event-index errors against disclosed annotations.</li><li>Raw classifier and enrollment runtime, with exclusions.</li></ul></article></div>`) +
    section('limitations','What remains unproven', note('No representative field result is available','The fixture contains two historical query expectations. Generated vector cases test mechanisms. Neither establishes route accuracy across users, days, lighting, viewpoints or devices. No calibrated probability, real-time route-navigation benchmark or user-benefit result is claimed.') + `<div class="actions">${button('/docs/evaluation-plan.md','Dataset cards and methodology')}${button('/references.html','Prior art and primary references')}</div>`));

  const methodNames = {vxn_default:'VXN default',vxn_reference_windows:'Window recomputation reference',vxn_disjoint_best:'Disjoint + best window',vxn_legacy:'Legacy overlap + best',vxn_original_only:'Original-only ablation',vxn_no_temporal_prior:'No temporal prior',fixed_branch_a:'Fixed Branch A',global_centroid:'Global centroid',last_frame_nn:'Last-frame nearest neighbor',mean_frame_nn:'Mean nearest neighbor',dtw_suffix:'DTW suffix'};
  const evidenceSection = (name, heading, description) => {
    const report = reports[name];
    const rows = Object.entries(report.methods).map(([method, entry]) => {
      const m = entry.metrics, t = entry.classification_timing;
      return [escape(methodNames[method]), `${m.accepted} / ${m.journeys}`, String(m.accepted_errors), `${m.correct_known} / ${m.known_journeys}`, m.known_macro_f1 === null ? 'Undefined' : m.known_macro_f1.toFixed(3), m.unknown_journeys ? `${m.unknown_false_accepts} / ${m.unknown_journeys}` : 'Undefined (no unknowns)', `${t.median_ms.toFixed(3)} ms`, `${t.p95_ms.toFixed(3)} ms`];
    });
    return section(name,heading, `<p>${description}</p>${table(['Method','Accepted / total','Accepted errors','Correct known / known','Known macro F1','Unknown accepts / unknown','Median','p95'],rows,`${heading}: executed results`)}<figure class="diagram"><img src="/evidence/${name}/figures/classifier-runtime.png" alt="Measured local cached classifier runtime for ${heading}; excludes encoder and mobile inference" loading="lazy"><figcaption>Actual recorded median classifier timings. Log scale; these diagnostic workloads do not establish mobile or field performance.</figcaption></figure><p class="small">Timing excludes video decoding, EfficientNet, Wi-Fi, Android and speech. ${report.repeats} measured repeats and ${report.warmups} warm-up per journey; repeated timings do not create new journeys. Shared thresholds are diagnostic across differing score scales.</p><div class="actions">${button(`/evidence/${name}/report.json`,'Full report JSON')}${button(`/evidence/${name}/decisions.csv`,'Journey decisions CSV')}${button(`/evidence/${name}/timings.csv`,'Raw timing samples')}${button(`/evidence/${name}/threshold-sweep.csv`,'Threshold sweep')}${button(`/evidence/${name}/checksums.json`,'Artifact checksums')}</div>`);
  };
  const evidence = make('evidence.html','Executed tests and bounded benchmark results','Actual executed VXN-RAMNet regression and synthetic benchmark results, baseline outcomes, denominators, raw timings and reproducible artifacts.', intro('Evidence · actual executions','Results with their denominators<br>and their limits.',`Every numeric table is rendered from saved evaluation JSON. These are regression and synthetic diagnostics. Representative held-out camera-route accuracy, calibrated uncertainty and live mobile route performance remain unestablished.`) +
    section('verification','Software verification', `<div class="verification-grid"><div><span>Passing local tests</span><strong>${release.verification.pytest.tests}</strong><small>${release.verification.pytest.skipped} skipped in the recorded full run</small></div><div><span>Package coverage</span><strong>${release.verification.coverage.percent_covered.toFixed(2)}%</strong><small>Statements + branches; no package-file omissions</small></div><div><span>Checks</span><strong>Passed</strong><small>Lint, format, typing, dependency check and package build</small></div></div><p>Encoder smoke tests exercised actual ImageNet inference and local-weight descriptor parity. Video pipeline integration used an injectable synthetic encoder; it is not a field navigation test.</p><div class="actions">${button('/evidence/verification/checks.json','Recorded verification')}${button('/evidence/verification/pytest.xml','JUnit test record')}${button('/evidence/verification/coverage.json','Coverage details')}${button('/evidence/judge-pack.json','Judge-pack manifest')}${button('/source.html','Matching source excerpts')}</div>${note('Compact deployment, preserved raw evidence','The website serves the artifacts needed to inspect claims quickly. High-volume per-query JSON, NPZ memories and fixture arrays are retained in the source-package archive with its SHA-256 recorded in the judge-pack manifest; they are intentionally not uploaded to Vercel.')}`) +
    evidenceSection('notebook04','Historical cached fixture','270 enrollment descriptors and two 120-descriptor queries, each 1,280-dimensional. Labels and event anchors are inherited regression expectations. Raw videos, acquisition sessions, independently annotated truth and the original weight hash were not supplied. Unknown-route metrics are undefined because this fixture has no unknown queries.') +
    evidenceSection('synthetic','Generated vector stress cases','84 simulated queries: 48 known-branch, 24 unknown-vector and 12 ambiguous-vector cases. These 64-dimensional vectors use a fixed seed and a disclosed generator. They contain no camera images or real participants and do not establish field recognition performance.') +
    section('events','Event reproduction, without inferred time accuracy', table(['Variant','First junction','Turnaround','Junction revisit','Mean absolute anchor error'],Object.entries(reports.notebook04.enrollment).map(([v,e]) => [escape(v),String(e.events.first_junction_index),String(e.events.turnaround_index),String(e.events.return_junction_index),`${e.event_mean_absolute_error_frames} sampled frames`])) + `<p>Expected fixture anchors are 60, 134 and 193. Index agreement establishes regression fidelity; it is not independently annotated event-detection accuracy or a seconds-level measurement.</p>`) +
    section('risk','Read abstention together with error', `<p>Coverage is accepted decisions divided by all declared journeys. Selective risk is incorrect accepted decisions divided by accepted decisions. A method that refuses every query has zero coverage and undefined selective risk, rather than demonstrated perfect recognition.</p><p>Unknown false acceptance uses unknown journeys as its denominator. Ambiguous cases remain separately labeled. Confidence values are excluded from probability calibration claims.</p>${note('No superiority claim follows from these tables','The same hand-set thresholds are applied to methods with different score distributions. The tiny cached fixture and generated vector suite cannot establish gains on independent physical routes.')}<div class="actions">${button('/reproduce.html','Reproduce these artifacts',true)}${button('/docs/evaluation-plan.md','Full evaluation protocol')}</div>`));

  const demo = make('demo.html','Demo and recording status','A clearly labeled temporary YouTube hardware video plus reproducible VXN-RAMNet core demonstration instructions.', intro('Demo · recording status',config.demo.isPlaceholder ? 'VisionX recording pending.<br>Core reproduction available.' : 'VisionX demonstration.',config.demo.isPlaceholder ? 'The project owner asked for a temporary video until the designated recording is ready. The linked Raspberry Pi introduction is an external hardware video; it is not evidence of VisionX execution.' : 'Use the demonstration with the source, configuration, input and evidence records supplied alongside it.') +
    section('video',config.demo.isPlaceholder ? 'Temporary external hardware video' : 'Project demonstration', `<div class="video-card"><div class="video-symbol" aria-hidden="true">▶</div><div>${tag(config.demo.isPlaceholder ? 'Placeholder · not a VisionX demo' : 'Project recording',config.demo.isPlaceholder ? 'target' : 'core')}<h2>${escape(config.demo.title)}</h2><p>${escape(config.demo.note)}</p><p class="small">Credit: ${escape(config.demo.credit)}</p>${external(config.demo.url,config.demo.isPlaceholder ? 'Open temporary video on YouTube' : 'Watch VisionX on YouTube','button primary')}</div></div><p class="small">The video opens only when selected. No automatic redirect or embedded third-party tracker loads on this page.</p>`) +
    section('offline-demo','A core demo that judges can reproduce', `<ol class="detail-list"><li>Install the local package from the final repository ZIP.</li><li>Run the cached fixture evaluation without TensorFlow or raw recordings.</li><li>Inspect learned event indices, branch decisions, window evidence and baseline outcomes.</li><li>Generate the vector stress suite to inspect unknown and ambiguous cases.</li><li>For your own camera videos, install the vision extra, approve local weights and retain full provenance.</li></ol>${code('vxn-ramnet evaluate --manifest benchmarks/manifests/notebook04.json --output evidence/reproduced-notebook04 --repeats 5 --warmups 1')}<div class="actions">${button('/reproduce.html','Complete setup guide',true)}${button('/evidence.html','Actual saved outputs')}</div>`) +
    section('recording','The final recording should show the evidence boundary', `<p>A VisionX recording should identify the actual device, source revision, configuration and inputs. Show the current detection path separately from offline route recognition, and retain genuine refusal or failure outcomes.</p><p>Do not describe this cached-core replay as live wearable navigation. The team-reported approximately one-hour test is not a measured battery-life, latency or route-recognition result.</p>`));

  const reproduce = make('reproduce.html','Reproduce the research core','Clean installation, locked dependencies, testing, fixture and synthetic evaluations, raw-video pipeline and artifact reproduction instructions.', intro('Reproduce · no-login evidence','Reproduce the research core.','Start with cached descriptors. That path needs no TensorFlow, model download, raw video, GPS, Android device or wearable hardware. The full vision adapter is a separate optional installation.') +
    section('setup','1. Install from the delivered repository', code('python -m venv .venv\n# Windows: .venv\\Scripts\\Activate.ps1\n# macOS/Linux: source .venv/bin/activate\npython -m pip install -r requirements/core-dev.lock\npython -m pip install --no-deps -e .') + `<p>Use Python 3.11 or 3.12. Commands run from the extracted VXN-RAMNet root. The upstream GitHub repository may still reflect an earlier version until this release is uploaded; the bundled ZIP and source SHA identify these results.</p>`) +
    section('checks','2. Run engineering checks', code('python -m ruff check src tests scripts apps\npython -m ruff format --check src tests scripts apps\npython -m mypy src/vxn_ramnet\npython -m pytest -m "not vision" --cov=vxn_ramnet\npython -m build') + `<p>The optional UI test skips when Streamlit is absent. The optional encoder test requires TensorFlow and explicit permission through <code>VISIONX_TEST_IMAGENET=1</code> to resolve ImageNet weights.</p>`) +
    section('fixture','3. Reproduce the cached fixture', code('vxn-ramnet evaluate --manifest benchmarks/manifests/notebook04.json --output evidence/reproduced-notebook04 --repeats 5 --warmups 1') + `<p>The output must be a fresh directory. Inputs are validated before evidence creation. Decisions, event indices and hashes should match under the pinned environment; runtime measurements vary with the machine and load.</p>`) +
    section('synthetic','4. Generate and evaluate vector stress cases', code('vxn-ramnet generate-synthetic --output data/synthetic --seed 2026\nvxn-ramnet evaluate --manifest data/synthetic/manifest.json --output evidence/reproduced-synthetic --repeats 5 --warmups 1') + `<p>The generated dataset is explicitly synthetic. It tests mechanisms and is excluded from any claim of independently recorded camera-route performance.</p>`) +
    section('video','5. Run your own completed videos', code('python -m pip install -r requirements/vision-ui.lock\npython -m pip install --no-deps -e .\nvxn-ramnet validate-config --config configs/camera_baseline.yaml\nvxn-ramnet run --config configs/camera_baseline.yaml\n# Optional local UI:\nstreamlit run apps/streamlit_app.py') + `<p>Supply your own learning and query recordings and edit the configuration. Relative project roots resolve from the configuration file. Use approved local weights for network-independent inference after setup. No raw videos or model-weight files are included.</p>`) +
    section('outputs','6. Inspect the artifacts', table(['Artifact','Purpose'],[['config.snapshot.json + resume-identity.json','Configuration, input/model/source/dependency identity'],['inputs/frame-extraction.json','Sampled source indices and nominal frame timestamps; decode provenance'],['memory/route-memory.npz + .json','Five-component memory with checksums and validated metadata'],['reports/summary.json + query-results.csv + report.md','Decisions with scores, selected windows and limitations'],['stages/*.json + logs/pipeline.jsonl','Stage status, elapsed time and output hashes'],['Evaluation report.json + decisions.csv + timings.csv','Journey-level metrics and actual runtime samples']]) + `<div class="actions">${button('/docs/reproduction.md','Download the full guide')}${repo}</div>`));

  const business = make('business.html','Proposed institutional deployment model','VisionX proposed campus evaluation and conditional institutional pilot, cost and support requirements, without fabricated pricing or traction.', intro('Deployment · proposed model','An institutional pilot<br>conditional on evidence.','The first proposed setting is a controlled campus route with one junction and two taught branches. Institutions may coordinate evaluation, enrollment and support, if a real user need and technical benefit are demonstrated.') +
    section('path','Evidence gates before deployment', `<ol class="gate-list"><li><span>01</span><div><h3>Evaluate the route task</h3><p>Collect independent sessions, unknowns and failure cases. Compare fair baselines and report accepted error with coverage.</p></div></li><li><span>02</span><div><h3>Validate mobile and wearable integration</h3><p>Establish conversion parity, causal inference, stream freshness, fault recovery, sustained resources and a safe physical setup.</p></div></li><li><span>03</span><div><h3>Co-design and supervise</h3><p>Work with consenting users and mobility expertise. Measure comprehension, wrong turns, interventions, workload, preference and enrollment effort.</p></div></li><li><span>04</span><div><h3>Pilot a bounded supported service</h3><p>Only after usefulness and full cost are demonstrated: define route scope, named devices, maintenance, rollback, training and support ownership.</p></div></li></ol>`) +
    section('revenue','Conditional revenue options',table(['Proposal','Possible payer','Evidence still needed'],[['Evaluation engagement','Institution or research sponsor','Agreed scope, supervision and measurements'],['Supported kit or managed loan','Institution','Validated BOM, assembly, repair and support cost'],['Enrollment and training','Institution or deployment partner','Measured staff effort and accessible workflow'],['Maintenance agreement','Institution','Actual recurring support and route revalidation needs'],['Later SDK licensing','Integrator','Stable contracts, rights review and demonstrated demand']])) +
    section('unknowns','Commercial outcomes remain unknown',note('No pricing or traction is claimed','No validated selling price, cost saving, paying demand, revenue, partnership, subsidy entitlement or government endorsement was supplied. Full phone, enclosure, power, sensor, assembly, enrollment and support costs need measurement.') + `<p>Compare the wearable against a simpler phone-only approach and users’ existing mobility strategies. If those serve the task better, narrow the wearable proposal. Scaling deployments does not establish a general multi-junction navigation engine.</p>`) +
    section('impact','Expected benefits, with validation boundaries',figure('presentation/VisionX_04_Impact_Benefits.svg','VisionX expected social economic environmental benefits with core, live-test and target evidence boundaries','Supplied impact diagram. User benefit, affordability and net environmental outcomes remain unmeasured.') + `<div class="actions">${button('/docs/business-model.md','Business model and cost framework')}${button('/references.html','Supporting research')}</div>`));

  const referenceRows = [
    ['WHO: vision impairment','https://www.who.int/news-room/fact-sheets/detail/blindness-and-visual-impairment','Accessibility context. Global prevalence is not VisionX’s addressable market.'],
    ['Indoor navigation needs (2020)','https://www.mdpi.com/1424-8220/20/3/636','User-needs framing and existing indoor navigation approaches; no VisionX efficacy result.'],
    ['Clew: recorded-route retracing','https://github.com/occamLab/Clew','Recorded-path assistance is established prior art; current app behavior is not independently tested here.'],
    ['SeqSLAM (2012)','https://ieeexplore.ieee.org/document/6224623/','Sequence-based visual route recognition predates this project. DTW here is not SeqSLAM.'],
    ['Selective classification (2017)','https://arxiv.org/abs/1705.08500','Motivates risk with coverage; its theoretical guarantees are not implemented by VXN-RAMNet.'],
    ['Keras EfficientNetB0','https://keras.io/api/applications/efficientnet/efficientnet_models/','Encoder and preprocessing reference; not route-recognition accuracy.'],
    ['Raspberry Pi Zero 2 W','https://www.raspberrypi.com/products/raspberry-pi-zero-2-w/','Board interfaces and capture/transport feasibility; not achieved application speed or battery life.'],
    ['Android offline voices','https://developer.android.com/reference/android/speech/tts/Voice','Voice network-dependency API; a provisioned offline voice still needs device testing.'],
    ['LiteRT: target runtime','https://developers.google.com/edge/litert/android','Potential Android runtime path. No validated VXN mobile export is included.'],
  ];
  const references = make('references.html','Research references and claim register','Primary research and component references aligned with the VisionX presentation, with implementation and validation limits for each source.',intro('References · primary sources','Each source has a defined role.','External papers and official component documentation explain prior art, user needs and technical options. They do not validate VisionX implementation, route accuracy, safety, pricing or user benefit.') +
    section('presentation','The presentation’s nine reference topics',table(['Source','Role and limit'],referenceRows.map(([title,url,role]) => [external(url,title),role]))) +
    section('traceability','Project claims use project evidence',table(['Claim','Inspectable implementation / evidence','Limit'],[
      ['Structured personal route memory','<a href="/source.html#recognition">Shared learning / recognition API</a> · <a href="/evidence.html#events">Event anchors</a>','One junction, two exploration-order branches.'],
      ['Branch-aware recall','<a href="/research.html#method">Method</a> · <a href="/evidence.html">All method results</a>','Held-out superiority unproven.'],
      ['Evidence-gated outcomes','<a href="/source.html#decision">Decision rules</a> · <a href="/evidence.html#risk">Coverage and accepted error</a>','Thresholds uncalibrated; no navigation safety guarantee.'],
      ['Phone-edge detection test','<a href="/architecture.html#current-paths">Current execution boundaries</a>','Team-reported hardware account. Pi and Android source were not supplied.'],
      ['Conditional deployment','<a href="/business.html">Business model</a>','No validated customer, price, partnership or user benefit.'],
    ]) + `<div class="actions">${button('/docs/claim-evidence-matrix.md','Complete PPT claim matrix')}${button('/docs/research-references.md','Source register')}${button('/docs/audit/analysis.md','Artifact reconciliation findings')}</div>`) +
    section('retrieval','Availability and provenance', `<p>Repository links consistently use <code>AjaySoniDev</code>. Local evidence files travel with this website, so reviewing numeric artifacts does not depend on the upstream repository having been updated.</p><p>Publisher sites may impose access restrictions. Reference roles are limited to the linked primary record or official documentation; no vendor or paper result is transferred to VisionX.</p>`));

  const sourceFiles = [['recognition','Shared route-memory API','recognition.py'],['decision','Abstention rules','algorithms/decision.py'],['evaluation','Evaluation runner','evaluation/runner.py'],['metrics','Metric denominators','evaluation/metrics.py']];
  const source = make('source.html','Exact release source excerpts','Exact source excerpts matching the VXN-RAMNet release source hash, including route recognition, abstention, evaluation and metric denominators.',intro('Implementation · release snapshot','Inspect the code behind the claims.',`These excerpts are copied byte-for-byte from the delivered repository. The source content identity is <code>${release.sourceSha256}</code>. This identifies the local release independently of a Git commit.`) +
    section('source-index','Source and evidence together', `<div class="actions">${sourceFiles.map(([id,title]) => button(`#${id}`,title)).join('')}${repo}</div><p>Download paths under <code>/evidence/source/vxn_ramnet/</code> contain this release’s complete Python package and JSON schemas. Tests and full repository documentation are in the repository ZIP.</p>`) +
    sourceFiles.map(([id,title,file]) => section(id,title, `<p><a href="/evidence/source/vxn_ramnet/${file}">Download ${escape(file)}</a> · SHA-256: <code class="break-code">${release.sourceFiles[file]}</code></p><details><summary>Read the complete ${escape(title.toLowerCase())}</summary><pre class="source-code" tabindex="0"><code>${escape(fs.readFileSync(path.join(root,'evidence/source/vxn_ramnet',file),'utf8'))}</code></pre></details>`)).join('') +
    section('tests','Tests behind the evidence', `<p>The readable test source is copied from the same delivered repository. The JUnit record identifies the actual executed cases and outcomes; large binary test fixtures remain in the checksummed offline evidence archive rather than the Vercel deployment.</p><div class="actions">${button('/evidence/verification/pytest.xml','Recorded JUnit outcomes')}${button('/evidence/tests/regression/test_notebook04_baseline.py','Historical regression test')}${button('/evidence/tests/integration/test_pipeline.py','Pipeline and resume tests')}${button('/evidence/tests/integration/test_evaluation.py','Executable evaluator tests')}${button('/evidence/tests/unit/test_evaluation_metrics.py','Metric denominator tests')}${button('/evidence/tests/unit/test_numerical_boundaries.py','Invalid data and artifact tests')}${button('/evidence/tests/vision/test_encoder.py','Real encoder parity test')}</div>`));

  const missing = make('404.html','Page unavailable','This VisionX evidence page could not be found. Return to the project, evidence or reproduction guide.',intro('404 · page unavailable','This page could not be found.','The project and its evidence remain available from the links below.') + section('recover','Continue your review',`<div class="actions">${button('/','Return to the project',true)}${button('/evidence.html','Inspect evidence')}${button('/reproduce.html','Reproduction guide')}</div>`));
  return [home,architecture,research,evidence,demo,reproduce,business,references,source,missing];
}
